name: AWS Lambda Deploy

on:
  workflow_run:
    workflows: [ "AWS Lambda Package" ]
    branches: [ main ]
    types:
      - completed

jobs:
  deploy:
    on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        role-duration-seconds: 1200
        role-session-name: MySessionName
    - name: AWS Lambda Deploy
      run: |
        aws lambda update-function-code --function-name expense-category-fetcher \
        --zip-file fileb://expense-category-fetcher.zip
    - name: Sleep for 20 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '20s'
    - name: AWS Lambda Update
      run: |
        aws lambda update-function-configuration --function-name expense-category-fetcher \
        --handler main.lambda_handler \
        --layers arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p38-matplotlib:14
