name: AWS Lambda Test

on:
  workflow_run:
    workflows: [ "AWS Lambda Deploy" ]
    branches: [ main ]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Test Lambda
        run: |
          # AWS Version check
          aws_version=$(aws --version)
          echo "$aws_version"

          # AWS CLI v2 command
          error_message=$(aws lambda invoke --function-name expense-category-fetcher \
          --invocation-type RequestResponse --payload file://events/test-sqs-event.json \
          --cli-binary-format raw-in-base64-out /tmp/lambda-response.txt | grep "FunctionError")
          echo "$error_message"

          # Exit if error received from Lambda invocation
          if [ -z "$error_message" ]
          then
            echo "Success returned from Lambda"
            exit 0
          else
            echo "Error returned from Lambda"
            exit 1
          fi